"use strict";
let cat = "simba";
let dog = "matata";
console.log(cat);
console.log(dog);
console.log(cat + " " + dog);
console.log("cat" + "dog");
let boy = 4567;
console.log(boy);
let house = "I own a modern house!";
console.log(house);
const news = Symbol("eating");
const ned = Symbol("dinner");
console.log(ned === news);
